### ISSUE TITLE
iOS8 & Autolayout

### ISSUE THREAD

**Issue by mineschan** [mineschan/MZTimerLabel#21]
As apple release iOS8 and the way to work with size classes, does anyone have issue on implementing MZTimerlabel using iOS8 + auto layout? If so, any suggestions?

**Comment by strife25** [comment]
Are you looking for help on this or just asking to see if the community is interested in this support?

If it's the latter, I am +1 for that - auto layout is the recommended layout tech that they want consumers to use. Once you understand the APIs, it's really not that bad (although debugging it is not fun). 

FWIW, there is not much to do here w/r/t MZTimerLabel's support from what I see. Since it's a subclass of UILabel, I just do the following to get it to work w/ auto layout:

```
myTimerLabel.translatesAutoresizingMaskIntoConstraints = NO;
```

This is a normal pattern for people consuming auto layout from what I understand.

**Comment by mineschan** [comment]
Yeh I think so. MZTimerLabel should obey to UILabel auto layout behaviour.
